# Example server config file
host: ''
port: 8022
clients:
  # This are just examples. Please generate your own keypair for each client you want to add
  example1: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFY33xLzFiLk5GnNu2Bm8Ns3TMSILtU6p1WItgy6sPMP
  example2: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMDV1fTeb7PiYVnqzGTQzdw5r3VPSaDFgfoPm1GD6HaR
